/**
 * Regenerates `registry.ts` from the country files present on disk.
 *
 * The registry is a pure index: every country file has to be listed there, and
 * the key must equal `countries.name` exactly or the seed skips it. Writing it
 * by hand is error-prone and, when several authors add files at once, a
 * guaranteed merge conflict — so it is derived instead.
 *
 * Run with `npx tsx prisma/seeds/visa-steps/build-registry.ts`.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const DIR = __dirname;
const NOT_A_COUNTRY = new Set([
  'index.ts',
  'registry.ts',
  'types.ts',
  'validate.ts',
  'build-registry.ts',
]);

/** Country names exactly as they appear in the country seed. */
function countryNames(): string[] {
  const source = readFileSync(join(DIR, '..', 'countries.seed.ts'), 'utf8');
  return [...source.matchAll(/^ {6}name: '(.+)',$/gm)].map((m) => m[1]);
}

const slug = (name: string) =>
  name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');

const bySlug = new Map(countryNames().map((name) => [slug(name), name]));

const entries = readdirSync(DIR)
  .filter((file) => file.endsWith('.ts') && !NOT_A_COUNTRY.has(file))
  .map((file) => {
    const base = file.replace(/\.ts$/, '');
    const country = bySlug.get(base);

    // A file whose name does not match any seeded country would be imported and
    // then silently ignored, so fail loudly instead.
    if (!country) {
      throw new Error(
        `${file}: no country in countries.seed.ts matches this filename. Rename the file to the slug of the country name.`,
      );
    }

    const exported = /export const (\w+): CountryVisaSteps/.exec(
      readFileSync(join(DIR, file), 'utf8'),
    );
    if (!exported) {
      throw new Error(
        `${file}: no "export const <name>: CountryVisaSteps" found.`,
      );
    }

    return { file: base, symbol: exported[1], country };
  })
  .sort((a, b) => a.symbol.localeCompare(b.symbol));

const needsQuotes = (name: string) => !/^[A-Za-z_$][\w$]*$/.test(name);

const source = `import type { CountryVisaSteps } from './types';
${entries.map((e) => `import { ${e.symbol} } from './${e.file}';`).join('\n')}

/**
 * One entry per country, keyed by \`countries.name\` exactly as it appears in
 * \`countries.seed.ts\`. Splitting by country keeps each file reviewable and each
 * diff scoped to the country that actually changed.
 *
 * A country absent from here simply has no steps seeded. The seed is additive,
 * so filling this in over several rounds leaves no intermediate state that is
 * wrong — only incomplete.
 *
 * Generated by \`build-registry.ts\` from the files in this directory. Do not
 * edit by hand: add the country file and re-run the generator.
 *
 * Kept apart from \`index.ts\` so \`validate.ts\` can read it without constructing
 * a PrismaClient, which is what lets the checks run with no database.
 */
export const REGISTRY: Record<string, CountryVisaSteps> = {
${entries
  .sort((a, b) => a.country.localeCompare(b.country))
  .map(
    (e) =>
      `  ${needsQuotes(e.country) ? `'${e.country}'` : e.country}: ${e.symbol},`,
  )
  .join('\n')}
};
`;

writeFileSync(join(DIR, 'registry.ts'), source);
console.log(`registry.ts: ${entries.length} countries`);
