import type { CountryVisaSteps } from './types';

/**
 * Steps for Czechia.
 *
 * The employee card is the ordinary work route, and its first gate is not
 * paperwork but a vacancy: the post must be published in the central register
 * of jobs open to foreign nationals and have gone unfilled by Czech and EU
 * candidates. Self-employment is a genuinely different road, built on the
 * živnostenský list — the trade licence — which becomes the purpose of stay and
 * brings monthly social and health advances whether or not you earn anything.
 *
 * Two deadlines catch almost everyone. The foreign police have to be told where
 * you live within three working days of arriving, and the adaptation and
 * integration course has to be completed within a year of collecting the card.
 *
 * Consular appointments are the real bottleneck: slots are rationed by quota
 * and can be booked out for months, so the calendar, not the file, usually
 * decides when you move.
 */
export const czechia: CountryVisaSteps = {
  'Short-Stay Visa (Schengen Type C)': {
    core_documents: [
      {
        en: [
          'Valid passport',
          'Valid for at least three months beyond the intended departure, issued within the last ten years and with two free pages.',
        ],
        pt: [
          'Passaporte válido',
          'Válido por pelo menos três meses além da saída prevista, emitido nos últimos dez anos e com duas páginas livres.',
        ],
        es: [
          'Pasaporte vigente',
          'Vigente al menos tres meses más allá de la salida prevista, emitido en los últimos diez años y con dos páginas libres.',
        ],
      },
      {
        en: [
          'Completed Schengen application form',
          'Czech consulates want the form generated by their own system and printed from it; a generic copy downloaded elsewhere is turned away at the counter.',
        ],
        pt: [
          'Formulário Schengen preenchido',
          'Os consulados checos querem o formulário gerado pelo sistema deles e impresso a partir dele; uma cópia genérica baixada noutro lugar é recusada no balcão.',
        ],
        es: [
          'Formulario Schengen cumplimentado',
          'Los consulados checos quieren el formulario generado por su propio sistema e impreso desde él; una copia genérica descargada en otro sitio se rechaza en ventanilla.',
        ],
      },
      {
        en: [
          'Two photographs of 35 by 45 millimetres',
          'Recent, on a white background, and not previously used in another application.',
        ],
        pt: [
          'Duas fotografias de 35 por 45 milímetros',
          'Recentes, em fundo branco e não usadas antes noutro pedido.',
        ],
        es: [
          'Dos fotografías de 35 por 45 milímetros',
          'Recientes, con fondo blanco y no utilizadas antes en otra solicitud.',
        ],
      },
      {
        en: [
          'Travel insurance accepted by the Czech authorities',
          'Minimum cover of 30,000 euros including repatriation, from an insurer Czechia recognises. A policy from an unlisted company is a frequent and avoidable refusal.',
        ],
        pt: [
          'Seguro de viagem aceite pelas autoridades checas',
          'Cobertura mínima de 30 mil euros incluindo repatriamento, de uma seguradora que a Chéquia reconheça. Uma apólice de companhia fora da lista é motivo frequente e evitável de recusa.',
        ],
        es: [
          'Seguro de viaje aceptado por las autoridades checas',
          'Cobertura mínima de 30 mil euros incluida la repatriación, de una aseguradora que Chequia reconozca. Una póliza de una compañía no listada es un motivo de denegación frecuente y evitable.',
        ],
      },
      {
        en: [
          'Proof of accommodation for every night',
          'Hotel bookings, or an invitation (pozvání) that your host has verified with the foreign police inside Czechia. That verification takes weeks, so it cannot be left to the last moment.',
        ],
        pt: [
          'Comprovativo de alojamento para todas as noites',
          'Reservas de hotel, ou um convite (pozvání) que o anfitrião tenha verificado junto da polícia de estrangeiros na Chéquia. Essa verificação leva semanas, por isso não pode ficar para o último momento.',
        ],
        es: [
          'Comprobante de alojamiento para todas las noches',
          'Reservas de hotel, o una invitación (pozvání) que su anfitrión haya verificado ante la policía de extranjería en Chequia. Esa verificación tarda semanas, así que no puede dejarse para el final.',
        ],
      },
      {
        en: [
          'Return or onward ticket reservation',
          'A booking that matches the dates on the form; buying the ticket outright is not required.',
        ],
        pt: [
          'Reserva de bilhete de volta ou de continuação',
          'Uma reserva coerente com as datas do formulário; não é preciso comprar o bilhete.',
        ],
        es: [
          'Reserva de billete de vuelta o de continuación',
          'Una reserva coherente con las fechas del formulario; no hace falta comprar el billete.',
        ],
      },
      {
        en: [
          'Documents proving the purpose of the trip',
          'A conference registration, a business invitation, a tour booking. The purpose declared on the form has to be backed by something.',
        ],
        pt: [
          'Documentos que provem o objetivo da viagem',
          'Inscrição num congresso, convite de negócios, reserva de um circuito. O objetivo declarado no formulário tem de estar apoiado em algo.',
        ],
        es: [
          'Documentos que acrediten el objeto del viaje',
          'Inscripción a un congreso, invitación de negocios, reserva de un circuito. El objeto declarado en el formulario debe estar respaldado por algo.',
        ],
      },
    ],
    financial_requirements: [
      {
        en: [
          'Proof of funds for the whole stay',
          'Czech law fixes a daily sum derived from the subsistence minimum, with a higher amount for the first day. Confirm the current calculation rather than reusing an old figure.',
        ],
        pt: [
          'Comprovativo de recursos para toda a estada',
          'A lei checa fixa um valor diário derivado do mínimo de subsistência, com um montante maior no primeiro dia. Confirme o cálculo atual em vez de reutilizar um número antigo.',
        ],
        es: [
          'Comprobante de fondos para toda la estancia',
          'La ley checa fija una suma diaria derivada del mínimo vital, con un importe mayor para el primer día. Confirme el cálculo vigente en lugar de reutilizar una cifra antigua.',
        ],
      },
      {
        en: [
          'Bank statements and a card in your own name',
          'A payment card alone does not prove anything: it has to be shown together with statements evidencing the balance behind it.',
        ],
        pt: [
          'Extratos bancários e cartão em nome próprio',
          'Um cartão sozinho não prova nada: tem de ser apresentado junto com extratos que comprovem o saldo por trás dele.',
        ],
        es: [
          'Extractos bancarios y tarjeta a su propio nombre',
          'Una tarjeta por sí sola no prueba nada: debe presentarse junto con extractos que acrediten el saldo que la respalda.',
        ],
      },
      {
        en: [
          'Proof of employment or studies at home',
          'An employer letter with approved leave, or an enrolment certificate. It is what shows you have a reason to go back.',
        ],
        pt: [
          'Comprovativo de emprego ou estudos no país de origem',
          'Carta do empregador com férias aprovadas, ou declaração de matrícula. É o que mostra que você tem motivo para voltar.',
        ],
        es: [
          'Comprobante de empleo o estudios en su país',
          'Carta del empleador con vacaciones aprobadas, o certificado de matrícula. Es lo que demuestra que tiene motivos para regresar.',
        ],
        priority: 2,
      },
    ],
    submission_fees: [
      {
        en: [
          'Book a slot in the consulate booking system',
          'Appointments at Czech consulates are notoriously scarce and some are released only at fixed times of the month. Plan several weeks ahead of when you need to apply.',
        ],
        pt: [
          'Reservar vaga no sistema de agendamento do consulado',
          'As vagas nos consulados checos são notoriamente escassas e algumas só são libertadas em horários fixos do mês. Planeie várias semanas antes de precisar pedir.',
        ],
        es: [
          'Reservar hueco en el sistema de citas del consulado',
          'Las citas en los consulados checos son notoriamente escasas y algunas se liberan solo en momentos fijos del mes. Planifique varias semanas antes de necesitar solicitar.',
        ],
      },
      {
        en: [
          'Pay the visa fee',
          'Charged in local currency at the consulate rate and not refunded if the visa is refused.',
        ],
        pt: [
          'Pagar a taxa do visto',
          'Cobrada em moeda local pela taxa do consulado e não devolvida se o visto for recusado.',
        ],
        es: [
          'Pagar la tasa del visado',
          'Se cobra en moneda local al tipo del consulado y no se devuelve si deniegan el visado.',
        ],
      },
      {
        en: [
          'Lodge the application at the competent consulate',
          'No more than six months before travelling and at least fifteen days ahead. Czechia insists on the consulate that covers your legal residence, not the most convenient one.',
        ],
        pt: [
          'Entregar o pedido no consulado competente',
          'No máximo seis meses antes da viagem e pelo menos quinze dias antes. A Chéquia exige o consulado que cobre a sua residência legal, não o mais conveniente.',
        ],
        es: [
          'Presentar la solicitud en el consulado competente',
          'Como mucho seis meses antes de viajar y al menos quince días antes. Chequia exige el consulado que cubre su residencia legal, no el más cómodo.',
        ],
      },
      {
        en: [
          'Allow for the decision to stretch beyond fifteen days',
          'The standard period can be extended to 45 days when the file is sent for additional checks, and there is no way to speed it up.',
        ],
        pt: [
          'Contar com a decisão a passar dos quinze dias',
          'O prazo padrão pode ser alargado para 45 dias quando o processo segue para verificações adicionais, e não há como acelerar.',
        ],
        es: [
          'Contar con que la decisión pase de quince días',
          'El plazo estándar puede ampliarse a 45 días cuando el expediente pasa a comprobaciones adicionales, y no hay forma de acelerarlo.',
        ],
      },
    ],
    biometrics_health: [
      {
        en: [
          'Fingerprint capture at the appointment',
          'Stored for 59 months and reused in later Schengen applications, including those made to other member states.',
        ],
        pt: [
          'Recolha de impressões digitais no atendimento',
          'Guardadas por 59 meses e reutilizadas em pedidos Schengen posteriores, incluindo os feitos a outros Estados-membros.',
        ],
        es: [
          'Toma de huellas dactilares en la cita',
          'Se conservan 59 meses y se reutilizan en solicitudes Schengen posteriores, incluidas las hechas a otros Estados miembros.',
        ],
      },
      {
        en: [
          'Medical examination',
          'Not part of a short-stay file; it belongs to the long-term categories.',
        ],
        pt: [
          'Exame médico',
          'Não faz parte de um processo de curta duração; pertence às categorias de longa duração.',
        ],
        es: [
          'Examen médico',
          'No forma parte de un expediente de corta duración; pertenece a las categorías de larga duración.',
        ],
        priority: 3,
        required: false,
      },
    ],
    post_approval_steps: [
      {
        en: [
          'Check the visa sticker details',
          'Number of entries, total days and validity window. The days granted are often fewer than the validity period suggests.',
        ],
        pt: [
          'Conferir os dados da vinheta do visto',
          'Número de entradas, total de dias e janela de validade. Os dias concedidos são muitas vezes menos do que o período de validade sugere.',
        ],
        es: [
          'Revisar los datos de la etiqueta del visado',
          'Número de entradas, días totales y ventana de validez. Los días concedidos suelen ser menos de lo que sugiere el periodo de validez.',
        ],
      },
      {
        en: [
          'Register with the foreign police within three working days',
          'Required unless your hotel or landlord reports you. Czechia enforces this far more than most Schengen states and a missing registration resurfaces at your next application.',
        ],
        pt: [
          'Registar-se na polícia de estrangeiros em três dias úteis',
          'Obrigatório a menos que o hotel ou o senhorio o comunique. A Chéquia fiscaliza isto muito mais do que a maioria dos Estados Schengen e um registo em falta reaparece no pedido seguinte.',
        ],
        es: [
          'Registrarse en la policía de extranjería en tres días hábiles',
          'Obligatorio salvo que su hotel o casero lo comunique. Chequia lo fiscaliza mucho más que la mayoría de Estados Schengen y un registro que falte reaparece en su siguiente solicitud.',
        ],
      },
      {
        en: [
          'Keep the insurance valid for the entire stay',
          'Police checks can ask for proof of cover at any moment, not only at the border crossing.',
        ],
        pt: [
          'Manter o seguro válido durante toda a estada',
          'Controlos policiais podem pedir prova de cobertura a qualquer momento, não apenas na fronteira.',
        ],
        es: [
          'Mantener el seguro vigente durante toda la estancia',
          'Los controles policiales pueden pedir prueba de cobertura en cualquier momento, no solo en la frontera.',
        ],
      },
      {
        en: [
          'Respect the 90 days in any 180 rule',
          'Counted on a rolling basis across the whole Schengen area, including days spent before entering Czechia.',
        ],
        pt: [
          'Respeitar a regra dos 90 dias em cada 180',
          'Contados de forma móvel em todo o espaço Schengen, incluindo dias passados antes de entrar na Chéquia.',
        ],
        es: [
          'Respetar la regla de 90 días en cada 180',
          'Se cuentan de forma móvil en todo el espacio Schengen, incluidos los días pasados antes de entrar en Chequia.',
        ],
      },
      {
        en: [
          'Do not work or trade on this visa',
          'Any employment or self-employment needs a long-term permit obtained beforehand; a short-stay visa never authorises either.',
        ],
        pt: [
          'Não trabalhar nem exercer atividade com este visto',
          'Qualquer emprego ou atividade por conta própria exige uma autorização de longa duração obtida antes; um visto de curta duração nunca autoriza nenhum dos dois.',
        ],
        es: [
          'No trabajar ni ejercer actividad con este visado',
          'Cualquier empleo o actividad por cuenta propia exige un permiso de larga duración obtenido antes; un visado de corta duración nunca autoriza ninguno de los dos.',
        ],
      },
    ],
  },

  'Long-Term Visa / Employee Card': {
    core_documents: [
      {
        en: [
          'Find a vacancy in the central register of jobs',
          'The post has to be published in the central register of vacancies open to employee card holders and to have gone unfilled by Czech and EU candidates for the set period. Without that entry the application cannot even be lodged.',
        ],
        pt: [
          'Encontrar uma vaga no registo central de empregos',
          'A vaga tem de estar publicada no registo central de posições abertas a titulares de employee card e ter ficado por preencher por candidatos checos e da UE pelo período definido. Sem esse registo o pedido nem pode ser entregue.',
        ],
        es: [
          'Encontrar una vacante en el registro central de empleos',
          'El puesto debe estar publicado en el registro central de vacantes abiertas a titulares de employee card y haber quedado sin cubrir por candidatos checos y de la UE durante el periodo fijado. Sin esa inscripción la solicitud ni siquiera puede presentarse.',
        ],
      },
      {
        en: [
          'Valid passport for the employee card',
          'It must cover the period requested; the card is never granted beyond the passport validity.',
        ],
        pt: [
          'Passaporte válido para o employee card',
          'Tem de cobrir o período pedido; o cartão nunca é concedido além da validade do passaporte.',
        ],
        es: [
          'Pasaporte vigente para el employee card',
          'Debe cubrir el periodo solicitado; la tarjeta nunca se concede más allá de la vigencia del pasaporte.',
        ],
      },
      {
        en: [
          'Employment contract of at least fifteen hours a week',
          'A contract, or a binding agreement to conclude one, stating the weekly hours and pay that meets the guaranteed wage for the job group.',
        ],
        pt: [
          'Contrato de trabalho de pelo menos quinze horas semanais',
          'Um contrato, ou um acordo vinculativo de o celebrar, indicando as horas semanais e uma remuneração que cumpra o salário garantido do grupo de funções.',
        ],
        es: [
          'Contrato de trabajo de al menos quince horas semanales',
          'Un contrato, o un acuerdo vinculante de celebrarlo, que indique las horas semanales y una retribución que cumpla el salario garantizado del grupo de puestos.',
        ],
      },
      {
        en: [
          'Accommodation proof with a notarised signature',
          'The owner consent form needs the signature officially verified at a Czech Point counter or by a notary. A plain lease with no verification is regularly rejected.',
        ],
        pt: [
          'Comprovativo de alojamento com assinatura reconhecida',
          'O termo de consentimento do proprietário precisa da assinatura reconhecida num balcão Czech Point ou por notário. Um contrato simples sem reconhecimento é rejeitado com frequência.',
        ],
        es: [
          'Comprobante de alojamiento con firma legitimada',
          'El consentimiento del propietario necesita la firma legitimada en una ventanilla Czech Point o ante notario. Un contrato simple sin legitimación se rechaza con frecuencia.',
        ],
      },
      {
        en: [
          'Documents proving qualification for the post',
          'Diplomas, professional certificates or evidence of practice matching the classification written in the contract.',
        ],
        pt: [
          'Documentos que provem a qualificação para a função',
          'Diplomas, certificados profissionais ou prova de prática correspondentes à classificação escrita no contrato.',
        ],
        es: [
          'Documentos que acrediten la cualificación para el puesto',
          'Títulos, certificados profesionales o pruebas de experiencia que correspondan a la clasificación escrita en el contrato.',
        ],
      },
      {
        en: [
          'Criminal record with apostille and Czech translation',
          'From your country of nationality and from anywhere you lived more than six months in the last three years, translated by a court-appointed translator.',
        ],
        pt: [
          'Certidão criminal com apostila e tradução para checo',
          'Do país da sua nacionalidade e de qualquer lugar onde tenha vivido mais de seis meses nos últimos três anos, traduzida por tradutor nomeado pelo tribunal.',
        ],
        es: [
          'Certificado de antecedentes con apostilla y traducción al checo',
          'De su país de nacionalidad y de cualquier lugar donde haya vivido más de seis meses en los últimos tres años, traducido por un traductor nombrado por el tribunal.',
        ],
      },
      {
        en: [
          'Employee card application form in Czech',
          'The form is filled in Czech even when the whole file is otherwise in another language; errors on it delay the case.',
        ],
        pt: [
          'Formulário de pedido do employee card em checo',
          'O formulário é preenchido em checo mesmo quando o resto do processo está noutra língua; erros nele atrasam o caso.',
        ],
        es: [
          'Formulario de solicitud del employee card en checo',
          'El formulario se rellena en checo aunque el resto del expediente esté en otro idioma; los errores en él retrasan el caso.',
        ],
      },
    ],
    education: [
      {
        en: [
          'Nostrification of the foreign diploma',
          'Recognition by a Czech university or a regional authority is required for regulated posts and for many qualified ones. It routinely takes several months and cannot be started after arrival.',
        ],
        pt: [
          'Nostrificação do diploma estrangeiro',
          'O reconhecimento por uma universidade checa ou autoridade regional é exigido para funções regulamentadas e para muitas qualificadas. Costuma levar vários meses e não pode ser iniciado depois da chegada.',
        ],
        es: [
          'Nostrificación del título extranjero',
          'El reconocimiento por una universidad checa o una autoridad regional se exige para puestos regulados y para muchos cualificados. Suele llevar varios meses y no puede iniciarse tras la llegada.',
        ],
      },
      {
        en: [
          'Recognition of a vocational qualification',
          'Trades and technical roles go through a separate recognition path rather than the university one.',
        ],
        pt: [
          'Reconhecimento de qualificação profissional',
          'Ofícios e funções técnicas seguem um caminho de reconhecimento separado, e não o universitário.',
        ],
        es: [
          'Reconocimiento de una cualificación profesional',
          'Los oficios y puestos técnicos siguen una vía de reconocimiento distinta de la universitaria.',
        ],
        priority: 2,
        required: false,
      },
    ],
    financial_requirements: [
      {
        en: [
          'Salary at the guaranteed wage for the job group',
          'Czech law sets guaranteed wage levels by job group, so a salary above the general minimum can still be too low for your classification. Check the level for the group written in the contract.',
        ],
        pt: [
          'Salário no nível garantido do grupo de funções',
          'A lei checa define níveis de salário garantido por grupo de funções, por isso um salário acima do mínimo geral pode ainda ser baixo demais para a sua classificação. Verifique o nível do grupo escrito no contrato.',
        ],
        es: [
          'Salario en el nivel garantizado del grupo de puestos',
          'La ley checa fija niveles de salario garantizado por grupo de puestos, así que un salario por encima del mínimo general puede seguir siendo bajo para su clasificación. Compruebe el nivel del grupo escrito en el contrato.',
        ],
      },
      {
        en: [
          'Pay the administrative fee for the application',
          'Paid at the embassy when the file is lodged and not returned if the card is refused.',
        ],
        pt: [
          'Pagar a taxa administrativa do pedido',
          'Paga na embaixada na entrega do processo e não devolvida se o cartão for recusado.',
        ],
        es: [
          'Pagar la tasa administrativa de la solicitud',
          'Se paga en la embajada al presentar el expediente y no se devuelve si deniegan la tarjeta.',
        ],
      },
    ],
    submission_fees: [
      {
        en: [
          'Book the embassy appointment for the employee card',
          'Slots are managed by quotas per country and per programme and can be booked out for months. The quota, not the paperwork, is usually what sets your timeline.',
        ],
        pt: [
          'Agendar na embaixada para o employee card',
          'As vagas são geridas por quotas por país e por programa e podem estar esgotadas por meses. É a quota, não a papelada, que costuma definir o seu calendário.',
        ],
        es: [
          'Reservar cita en la embajada para el employee card',
          'Los huecos se gestionan por cuotas por país y por programa y pueden estar agotados durante meses. La cuota, no el papeleo, suele marcar sus plazos.',
        ],
      },
      {
        en: [
          'Lodge the application in person at the embassy',
          'Filed at the mission covering your legal residence, with all originals presented at the counter.',
        ],
        pt: [
          'Entregar o pedido pessoalmente na embaixada',
          'Apresentado na missão que cobre a sua residência legal, com todos os originais mostrados no balcão.',
        ],
        es: [
          'Presentar la solicitud en persona en la embajada',
          'Se presenta en la misión que cubre su residencia legal, con todos los originales mostrados en ventanilla.',
        ],
      },
      {
        en: [
          'Allow sixty days or more for the decision',
          'The statutory period is sixty days from a complete file and longer in complicated cases. There is no fast track and no way to pay for one.',
        ],
        pt: [
          'Contar com sessenta dias ou mais para a decisão',
          'O prazo legal é de sessenta dias a contar do processo completo e maior em casos complicados. Não há via rápida nem forma de pagar por uma.',
        ],
        es: [
          'Contar con sesenta días o más para la resolución',
          'El plazo legal es de sesenta días desde el expediente completo y mayor en casos complicados. No hay vía rápida ni forma de pagar por una.',
        ],
      },
      {
        en: [
          'Collect the visa for collecting the residence permit',
          'A single-entry visa marked D/VR that only lets you enter and pick up the card. It is not the residence permit itself and expires quickly.',
        ],
        pt: [
          'Levantar o visto para recolher a autorização de residência',
          'Um visto de entrada única marcado D/VR que só permite entrar e levantar o cartão. Não é a autorização de residência em si e caduca depressa.',
        ],
        es: [
          'Recoger el visado para retirar el permiso de residencia',
          'Un visado de entrada única marcado D/VR que solo permite entrar y recoger la tarjeta. No es el permiso de residencia en sí y caduca pronto.',
        ],
      },
    ],
    biometrics_health: [
      {
        en: [
          'Biometrics at the Ministry of the Interior office',
          'Booked after arrival at the office for your region. The card is produced only after this appointment and takes weeks more to be ready.',
        ],
        pt: [
          'Biometria no posto do Ministério do Interior',
          'Agendada após a chegada no posto da sua região. O cartão só é produzido depois deste atendimento e leva mais semanas até ficar pronto.',
        ],
        es: [
          'Biometría en la oficina del Ministerio del Interior',
          'Se reserva tras la llegada en la oficina de su región. La tarjeta solo se produce después de esta cita y tarda semanas más en estar lista.',
        ],
      },
      {
        en: [
          'Travel insurance covering the gap before the card',
          'Required from entry until Czech public health insurance starts with your employment; the two rarely line up on the same day.',
        ],
        pt: [
          'Seguro de viagem para o intervalo antes do cartão',
          'Exigido desde a entrada até o seguro público de saúde checo começar com o emprego; os dois raramente coincidem no mesmo dia.',
        ],
        es: [
          'Seguro de viaje que cubra el hueco antes de la tarjeta',
          'Exigido desde la entrada hasta que el seguro público de salud checo empiece con el empleo; ambos rara vez coinciden el mismo día.',
        ],
      },
    ],
    post_approval_steps: [
      {
        en: [
          'Report your address to the foreign police in three days',
          'Within three working days of arrival, unless the accommodation provider does it for you. This is a separate obligation from the biometrics appointment.',
        ],
        pt: [
          'Comunicar a morada à polícia de estrangeiros em três dias',
          'Em três dias úteis após a chegada, a menos que o alojamento o faça por si. É uma obrigação separada do atendimento de biometria.',
        ],
        es: [
          'Comunicar su domicilio a la policía de extranjería en tres días',
          'En tres días hábiles desde la llegada, salvo que el alojamiento lo haga por usted. Es una obligación distinta de la cita de biometría.',
        ],
      },
      {
        en: [
          'Complete the adaptation and integration course',
          'Compulsory within one year of collecting the card for most new holders. Skipping it means a fine and awkward questions at renewal.',
        ],
        pt: [
          'Concluir o curso de adaptação e integração',
          'Obrigatório no prazo de um ano após levantar o cartão para a maioria dos novos titulares. Ignorá-lo significa multa e perguntas incómodas na renovação.',
        ],
        es: [
          'Completar el curso de adaptación e integración',
          'Obligatorio en el plazo de un año desde la recogida de la tarjeta para la mayoría de titulares nuevos. Saltárselo supone multa y preguntas incómodas en la renovación.',
        ],
      },
      {
        en: [
          'Notify the Ministry before changing employer or role',
          'The employee card is tied to the specific employer and position; a change needs prior notification and, in several cases, consent before you start.',
        ],
        pt: [
          'Avisar o Ministério antes de mudar de empregador ou função',
          'O employee card está ligado ao empregador e à posição específicos; uma mudança exige notificação prévia e, em vários casos, consentimento antes de começar.',
        ],
        es: [
          'Avisar al Ministerio antes de cambiar de empleador o puesto',
          'El employee card está ligado al empleador y al puesto concretos; un cambio exige notificación previa y, en varios casos, consentimiento antes de empezar.',
        ],
      },
      {
        en: [
          'Register with a Czech health insurance company',
          'The employer enrols you in the public system from the first day of work; check it actually happened, because gaps show up at renewal.',
        ],
        pt: [
          'Inscrever-se numa seguradora de saúde checa',
          'O empregador inscreve-o no sistema público desde o primeiro dia de trabalho; confirme que isso aconteceu mesmo, porque lacunas aparecem na renovação.',
        ],
        es: [
          'Darse de alta en una aseguradora de salud checa',
          'El empleador le inscribe en el sistema público desde el primer día de trabajo; compruebe que realmente ocurrió, porque los vacíos aparecen en la renovación.',
        ],
      },
      {
        en: [
          'Renew the employee card before it expires',
          'Filed at the Ministry of the Interior, ideally around ninety days ahead. Applying late costs you the continuity that permanent residence later depends on.',
        ],
        pt: [
          'Renovar o employee card antes de expirar',
          'Pedido no Ministério do Interior, idealmente cerca de noventa dias antes. Pedir tarde custa a continuidade de que a residência permanente depende mais adiante.',
        ],
        es: [
          'Renovar el employee card antes de que caduque',
          'Se presenta en el Ministerio del Interior, idealmente unos noventa días antes. Solicitar tarde le cuesta la continuidad de la que depende después la residencia permanente.',
        ],
      },
    ],
  },

  'Long-Term Business Visa (Trade Licence)': {
    core_documents: [
      {
        en: [
          'Obtain the živnostenský list (trade licence)',
          'Free trades are registered at any trade licensing office; craft, tied and concession trades need proof of qualification and sometimes a responsible representative. The licence is the purpose of stay, so it comes before the visa.',
        ],
        pt: [
          'Obter o živnostenský list (licença de atividade)',
          'As atividades livres registam-se em qualquer repartição de licenciamento; ofícios, atividades vinculadas e concessionadas exigem prova de qualificação e por vezes um representante responsável. A licença é o objetivo da estada, por isso vem antes do visto.',
        ],
        es: [
          'Obtener el živnostenský list (licencia de actividad)',
          'Las actividades libres se registran en cualquier oficina de licencias; los oficios, actividades vinculadas y concesionadas exigen prueba de cualificación y a veces un representante responsable. La licencia es el objeto de la estancia, así que va antes del visado.',
        ],
      },
      {
        en: [
          'Valid passport for the business visa',
          'With validity comfortably beyond the period you are asking for.',
        ],
        pt: [
          'Passaporte válido para o visto de negócios',
          'Com validade folgada para além do período que está a pedir.',
        ],
        es: [
          'Pasaporte vigente para el visado de negocios',
          'Con validez holgada más allá del periodo que solicita.',
        ],
      },
      {
        en: [
          'Business plan describing the intended activity',
          'The consular officer interviews you on it. A generic plan that does not match the trade you registered is the commonest way a business file falls apart.',
        ],
        pt: [
          'Plano de negócios descrevendo a atividade pretendida',
          'O funcionário consular entrevista-o sobre ele. Um plano genérico que não bate com a atividade registada é a forma mais comum de um processo de negócios desmoronar.',
        ],
        es: [
          'Plan de negocio que describa la actividad prevista',
          'El funcionario consular le entrevista sobre él. Un plan genérico que no coincide con la actividad registrada es la manera más habitual de que un expediente de negocios se venga abajo.',
        ],
      },
      {
        en: [
          'Accommodation consent with a verified signature',
          'The owner statement needs the signature officially verified, and the same address is what appears in the trade register as your place of business.',
        ],
        pt: [
          'Consentimento de alojamento com assinatura reconhecida',
          'A declaração do proprietário precisa da assinatura reconhecida, e a mesma morada é a que aparece no registo comercial como sede da atividade.',
        ],
        es: [
          'Consentimiento de alojamiento con firma legitimada',
          'La declaración del propietario necesita la firma legitimada, y esa misma dirección es la que figura en el registro mercantil como sede de la actividad.',
        ],
      },
      {
        en: [
          'Criminal record from home and a Czech extract',
          'The foreign certificate needs an apostille and a court translation; the Czech extract is drawn during the procedure.',
        ],
        pt: [
          'Certidão criminal do país de origem e extrato checo',
          'A certidão estrangeira precisa de apostila e tradução judicial; o extrato checo é obtido durante o procedimento.',
        ],
        es: [
          'Antecedentes del país de origen y extracto checo',
          'El certificado extranjero necesita apostilla y traducción judicial; el extracto checo se obtiene durante el procedimiento.',
        ],
      },
      {
        en: [
          'Long-term visa application form for business',
          'The business purpose has to be selected explicitly; a form filed under the wrong purpose cannot be corrected later.',
        ],
        pt: [
          'Formulário de visto de longa duração para negócios',
          'O objetivo de negócios tem de ser selecionado explicitamente; um formulário entregue com o objetivo errado não pode ser corrigido depois.',
        ],
        es: [
          'Formulario de visado de larga duración para negocios',
          'El objeto de negocios debe seleccionarse explícitamente; un formulario presentado con el objeto equivocado no puede corregirse después.',
        ],
      },
      {
        en: [
          'Company registration if you trade through an entity',
          'Working through a limited company instead of as a sole trader means the entry in the commercial register replaces part of the licence documentation.',
        ],
        pt: [
          'Registo da empresa se atuar através de uma sociedade',
          'Atuar por meio de uma sociedade em vez de empresário em nome individual faz com que a inscrição no registo comercial substitua parte da documentação da licença.',
        ],
        es: [
          'Registro de la sociedad si opera a través de una entidad',
          'Operar mediante una sociedad en lugar de como autónomo hace que la inscripción en el registro mercantil sustituya parte de la documentación de la licencia.',
        ],
        priority: 2,
        required: false,
      },
    ],
    education: [
      {
        en: [
          'Proof of qualification for a craft or regulated trade',
          'Free trades need nothing, but craft, tied and concession trades require documented training or years of practice in the field.',
        ],
        pt: [
          'Prova de qualificação para ofício ou atividade regulada',
          'As atividades livres não exigem nada, mas ofícios, atividades vinculadas e concessionadas exigem formação documentada ou anos de prática na área.',
        ],
        es: [
          'Prueba de cualificación para oficio o actividad regulada',
          'Las actividades libres no exigen nada, pero los oficios y actividades vinculadas y concesionadas exigen formación documentada o años de práctica en el sector.',
        ],
      },
      {
        en: [
          'Recognition of the qualification by the trade office',
          'Foreign training is assessed before the licence is issued, and that assessment is often what sets the start date of everything else.',
        ],
        pt: [
          'Reconhecimento da qualificação pela repartição de licenças',
          'A formação estrangeira é avaliada antes de a licença ser emitida, e essa avaliação é muitas vezes o que define a data de início de todo o resto.',
        ],
        es: [
          'Reconocimiento de la cualificación por la oficina de licencias',
          'La formación extranjera se evalúa antes de expedir la licencia, y esa evaluación suele marcar la fecha de inicio de todo lo demás.',
        ],
        priority: 2,
        required: false,
      },
    ],
    financial_requirements: [
      {
        en: [
          'Funds calculated over the length of the stay',
          'Czech rules multiply a sum derived from the subsistence minimum across the months requested and add accommodation costs. Confirm the current formula instead of relying on a fixed number.',
        ],
        pt: [
          'Recursos calculados pela duração da estada',
          'As regras checas multiplicam um valor derivado do mínimo de subsistência pelos meses pedidos e somam os custos de alojamento. Confirme a fórmula atual em vez de confiar num número fixo.',
        ],
        es: [
          'Fondos calculados según la duración de la estancia',
          'Las normas checas multiplican una suma derivada del mínimo vital por los meses solicitados y suman los costes de alojamiento. Confirme la fórmula vigente en vez de fiarse de una cifra fija.',
        ],
      },
      {
        en: [
          'Pay the administrative fee for the business visa',
          'Higher than the short-stay fee and payable at the embassy when the file is submitted.',
        ],
        pt: [
          'Pagar a taxa administrativa do visto de negócios',
          'Mais alta que a taxa de curta duração e paga na embaixada no momento da entrega do processo.',
        ],
        es: [
          'Pagar la tasa administrativa del visado de negocios',
          'Más alta que la tasa de corta duración y se abona en la embajada al presentar el expediente.',
        ],
      },
      {
        en: [
          'Register for tax, social security and health cover',
          'Within eight days of starting the trade. Self-employed people pay minimum monthly advances whether or not they made any profit that month.',
        ],
        pt: [
          'Inscrever-se em impostos, segurança social e saúde',
          'No prazo de oito dias após iniciar a atividade. Trabalhadores independentes pagam adiantamentos mensais mínimos independentemente de terem tido lucro no mês.',
        ],
        es: [
          'Darse de alta en hacienda, seguridad social y sanidad',
          'En el plazo de ocho días desde el inicio de la actividad. Los autónomos pagan anticipos mensuales mínimos con independencia de si tuvieron beneficio ese mes.',
        ],
      },
    ],
    submission_fees: [
      {
        en: [
          'Book the embassy slot for the business category',
          'Even scarcer than employee card slots, and at some missions released only through a periodic draw rather than first come first served.',
        ],
        pt: [
          'Reservar vaga na embaixada para a categoria de negócios',
          'Ainda mais escassa do que as vagas de employee card e, em algumas missões, libertada apenas por sorteio periódico em vez de por ordem de chegada.',
        ],
        es: [
          'Reservar hueco en la embajada para la categoría de negocios',
          'Aún más escaso que los huecos de employee card y, en algunas misiones, liberado solo mediante sorteo periódico en lugar de por orden de llegada.',
        ],
      },
      {
        en: [
          'Attend the interview about your business intent',
          'The officer probes whether the activity is genuine. Inconsistencies between the plan, the trade licence and your answers are what sink the file.',
        ],
        pt: [
          'Comparecer à entrevista sobre a intenção do negócio',
          'O funcionário sonda se a atividade é genuína. Incoerências entre o plano, a licença e as suas respostas são o que afunda o processo.',
        ],
        es: [
          'Acudir a la entrevista sobre su intención empresarial',
          'El funcionario sondea si la actividad es real. Las incoherencias entre el plan, la licencia y sus respuestas son lo que hunde el expediente.',
        ],
      },
      {
        en: [
          'Expect a decision period beyond three months',
          'Business files routinely run to the longer statutory limits, well past what an employee card takes.',
        ],
        pt: [
          'Esperar um prazo de decisão acima de três meses',
          'Os processos de negócios costumam chegar aos limites legais mais longos, bem além do que leva um employee card.',
        ],
        es: [
          'Esperar un plazo de resolución superior a tres meses',
          'Los expedientes de negocios suelen llegar a los límites legales más largos, bastante más de lo que tarda un employee card.',
        ],
      },
    ],
    biometrics_health: [
      {
        en: [
          'Biometrics for the long-term residence card',
          'Booked at a Ministry of the Interior office after entering on the collection visa.',
        ],
        pt: [
          'Biometria para o cartão de residência de longa duração',
          'Agendada num posto do Ministério do Interior após entrar com o visto de recolha.',
        ],
        es: [
          'Biometría para la tarjeta de residencia de larga duración',
          'Se reserva en una oficina del Ministerio del Interior tras entrar con el visado de recogida.',
        ],
      },
      {
        en: [
          'Insurance running continuously until the card arrives',
          'There is no employer to enrol you, so the self-employed have to keep a policy alive with no gap at all.',
        ],
        pt: [
          'Seguro contínuo até o cartão chegar',
          'Não há empregador para o inscrever, por isso o trabalhador independente tem de manter a apólice viva sem qualquer lacuna.',
        ],
        es: [
          'Seguro continuo hasta que llegue la tarjeta',
          'No hay empleador que le dé de alta, así que el autónomo debe mantener la póliza viva sin ningún vacío.',
        ],
      },
    ],
    post_approval_steps: [
      {
        en: [
          'Report to the foreign police after arriving',
          'Within three working days, at the office covering the district where you actually live.',
        ],
        pt: [
          'Apresentar-se à polícia de estrangeiros depois de chegar',
          'Em três dias úteis, no posto que cobre o distrito onde você realmente mora.',
        ],
        es: [
          'Presentarse ante la policía de extranjería tras llegar',
          'En tres días hábiles, en la oficina que cubre el distrito donde vive realmente.',
        ],
      },
      {
        en: [
          'Pay the minimum advances even in a bad year',
          'Social and health contributions have a floor for the self-employed regardless of turnover. Arrears are the single most common reason a renewal fails.',
        ],
        pt: [
          'Pagar os adiantamentos mínimos mesmo num ano ruim',
          'As contribuições sociais e de saúde têm um piso para os independentes, independentemente da faturação. Atrasos são o motivo mais comum de uma renovação falhar.',
        ],
        es: [
          'Pagar los anticipos mínimos incluso en un mal año',
          'Las cotizaciones sociales y sanitarias tienen un suelo para los autónomos, sea cual sea la facturación. Los atrasos son el motivo más común de que falle una renovación.',
        ],
      },
      {
        en: [
          'File the annual return and the two overviews',
          'The income tax return plus the social security and health insurance overviews. Renewals check that all three were filed on time.',
        ],
        pt: [
          'Entregar a declaração anual e os dois relatórios',
          'A declaração de imposto sobre o rendimento mais os relatórios da segurança social e do seguro de saúde. As renovações verificam se os três foram entregues no prazo.',
        ],
        es: [
          'Presentar la declaración anual y los dos resúmenes',
          'La declaración del impuesto sobre la renta más los resúmenes de la seguridad social y del seguro de salud. Las renovaciones comprueban que los tres se presentaron a tiempo.',
        ],
      },
      {
        en: [
          'Keep the trade licence active throughout',
          'Suspending the licence removes the purpose of stay, and the Ministry can end the residence before its printed expiry date.',
        ],
        pt: [
          'Manter a licença de atividade ativa o tempo todo',
          'Suspender a licença elimina o objetivo da estada, e o Ministério pode encerrar a residência antes da data de validade impressa.',
        ],
        es: [
          'Mantener la licencia de actividad activa todo el tiempo',
          'Suspender la licencia elimina el objeto de la estancia, y el Ministerio puede extinguir la residencia antes de la fecha de caducidad impresa.',
        ],
      },
      {
        en: [
          'Renew the long-term residence for business',
          'Proof of real income and paid contributions is what decides it. A dormant company with no turnover is refused however clean the paperwork looks.',
        ],
        pt: [
          'Renovar a residência de longa duração para negócios',
          'A prova de rendimento real e de contribuições pagas é o que decide. Uma empresa parada sem faturação é recusada por mais limpa que a papelada pareça.',
        ],
        es: [
          'Renovar la residencia de larga duración para negocios',
          'La prueba de ingresos reales y de cotizaciones pagadas es lo que decide. Una sociedad inactiva sin facturación se deniega por muy limpio que parezca el papeleo.',
        ],
      },
    ],
  },

  'Permanent Residence': {
    core_documents: [
      {
        en: [
          'Confirm five years of continuous long-term residence',
          'Time spent on a student long-term stay counts only at half, so many people reach the mark later than they planned. Long absences reduce the count as well.',
        ],
        pt: [
          'Confirmar cinco anos de residência contínua de longa duração',
          'O tempo com estada de longa duração para estudo conta apenas metade, por isso muita gente atinge a marca mais tarde do que planeou. Ausências longas também reduzem a contagem.',
        ],
        es: [
          'Confirmar cinco años de residencia continua de larga duración',
          'El tiempo con estancia de larga duración por estudios cuenta solo la mitad, así que mucha gente llega a la marca más tarde de lo previsto. Las ausencias largas también reducen el cómputo.',
        ],
      },
      {
        en: [
          'Valid passport and current biometric residence card',
          'Both in force on the day the application is registered at the office.',
        ],
        pt: [
          'Passaporte válido e cartão biométrico de residência atual',
          'Ambos em vigor no dia em que o pedido é registado no posto.',
        ],
        es: [
          'Pasaporte vigente y tarjeta biométrica de residencia actual',
          'Ambos en vigor el día en que se registra la solicitud en la oficina.',
        ],
      },
      {
        en: [
          'Permanent residence application at the Ministry office',
          'Filed with the Ministry of the Interior department for your region, in person, on their own form.',
        ],
        pt: [
          'Pedido de residência permanente no posto do Ministério',
          'Entregue no departamento do Ministério do Interior da sua região, presencialmente, no formulário próprio deles.',
        ],
        es: [
          'Solicitud de residencia permanente en la oficina del Ministerio',
          'Se presenta en el departamento del Ministerio del Interior de su región, en persona y en su propio formulario.',
        ],
      },
      {
        en: [
          'Accommodation proof for the permanent residence file',
          'A lease or title with the owner consent, signature verified, covering the address you are actually registered at.',
        ],
        pt: [
          'Comprovativo de alojamento para o processo de residência permanente',
          'Contrato ou título com consentimento do proprietário, assinatura reconhecida, referente à morada onde você está de facto registado.',
        ],
        es: [
          'Comprobante de alojamiento para el expediente de residencia permanente',
          'Contrato o título con consentimiento del propietario, firma legitimada, correspondiente a la dirección donde está realmente registrado.',
        ],
      },
      {
        en: [
          'Criminal record from Czechia and from abroad',
          'From every country where you lived more than six months in the last three years, with apostille and court translation.',
        ],
        pt: [
          'Certidão criminal da Chéquia e do estrangeiro',
          'De cada país onde viveu mais de seis meses nos últimos três anos, com apostila e tradução judicial.',
        ],
        es: [
          'Antecedentes penales de Chequia y del extranjero',
          'De cada país donde vivió más de seis meses en los últimos tres años, con apostilla y traducción judicial.',
        ],
      },
      {
        en: [
          'Two photographs for the permanent residence file',
          'To Czech specification and recent; old photos from the previous card are not reused.',
        ],
        pt: [
          'Duas fotografias para o processo de residência permanente',
          'Na especificação checa e recentes; fotos antigas do cartão anterior não são reaproveitadas.',
        ],
        es: [
          'Dos fotografías para el expediente de residencia permanente',
          'Según la especificación checa y recientes; no se reutilizan fotos antiguas de la tarjeta anterior.',
        ],
      },
      {
        en: [
          'Supporting proof where a shorter route applies',
          'Some routes reach permanent residence sooner, for family of Czech citizens or holders of particular statuses. Those files need their own evidence of the relationship or status.',
        ],
        pt: [
          'Prova de apoio quando se aplica uma via mais curta',
          'Algumas vias chegam à residência permanente mais cedo, para familiares de cidadãos checos ou titulares de determinados estatutos. Esses processos precisam da própria prova do vínculo ou do estatuto.',
        ],
        es: [
          'Prueba de apoyo cuando aplica una vía más corta',
          'Algunas vías llegan antes a la residencia permanente, para familiares de ciudadanos checos o titulares de ciertos estatutos. Esos expedientes necesitan su propia prueba del vínculo o del estatuto.',
        ],
        priority: 2,
        required: false,
      },
    ],
    education: [
      {
        en: [
          'Czech language exam at A2 level',
          'The required level rose to A2 and the exam is taken at an authorised school. The first attempt is covered by a voucher issued by the Ministry; a retake is paid out of pocket.',
        ],
        pt: [
          'Exame de checo no nível A2',
          'O nível exigido subiu para A2 e o exame é feito numa escola autorizada. A primeira tentativa é coberta por um voucher emitido pelo Ministério; a repetição é paga do próprio bolso.',
        ],
        es: [
          'Examen de checo en nivel A2',
          'El nivel exigido subió a A2 y el examen se realiza en una escuela autorizada. El primer intento lo cubre un bono emitido por el Ministerio; repetirlo se paga de su bolsillo.',
        ],
      },
      {
        en: [
          'Certificate of the integration course if still pending',
          'If you did not complete the adaptation course during the long-term stay, the certificate is asked for at this stage instead.',
        ],
        pt: [
          'Certificado do curso de integração se ainda estiver pendente',
          'Se não concluiu o curso de adaptação durante a estada de longa duração, o certificado é pedido nesta fase.',
        ],
        es: [
          'Certificado del curso de integración si sigue pendiente',
          'Si no completó el curso de adaptación durante la estancia de larga duración, el certificado se pide en esta fase.',
        ],
        priority: 2,
        required: false,
      },
    ],
    financial_requirements: [
      {
        en: [
          'Proof of regular income for the whole household',
          'Compared against the subsistence minimum plus reasonable housing costs for everyone living with you, so a good salary can still fail if the household is large.',
        ],
        pt: [
          'Prova de rendimento regular para todo o agregado',
          'Comparada com o mínimo de subsistência mais custos razoáveis de habitação para todos os que vivem consigo, por isso um bom salário pode ainda assim não bastar se o agregado for grande.',
        ],
        es: [
          'Prueba de ingresos regulares para todo el hogar',
          'Se compara con el mínimo vital más costes razonables de vivienda para todos los que conviven con usted, así que un buen salario puede no bastar si el hogar es grande.',
        ],
      },
      {
        en: [
          'Documents showing the source of that income',
          'Payslips, tax returns and confirmations from the tax office covering the qualifying period, not just the last few months.',
        ],
        pt: [
          'Documentos que mostrem a origem desse rendimento',
          'Recibos de vencimento, declarações fiscais e confirmações da administração fiscal cobrindo o período qualificado, não apenas os últimos meses.',
        ],
        es: [
          'Documentos que muestren el origen de esos ingresos',
          'Nóminas, declaraciones fiscales y certificados de hacienda que cubran el periodo cualificado, no solo los últimos meses.',
        ],
      },
      {
        en: [
          'Pay the fee for the permanent residence application',
          'Paid in administrative stamps at the office; confirm the amount in force before you go.',
        ],
        pt: [
          'Pagar a taxa do pedido de residência permanente',
          'Paga em selos administrativos no posto; confirme o valor vigente antes de ir.',
        ],
        es: [
          'Pagar la tasa de la solicitud de residencia permanente',
          'Se paga en sellos administrativos en la oficina; confirme el importe vigente antes de ir.',
        ],
      },
    ],
    submission_fees: [
      {
        en: [
          'Book the appointment at the Ministry office',
          'Slots are taken through the online system and disappear quickly, especially in Prague. Start looking well before your language certificate expires.',
        ],
        pt: [
          'Agendar atendimento no posto do Ministério',
          'As vagas são tiradas pelo sistema online e somem depressa, sobretudo em Praga. Comece a procurar bem antes de o seu certificado de idioma caducar.',
        ],
        es: [
          'Reservar cita en la oficina del Ministerio',
          'Los huecos se cogen por el sistema en línea y desaparecen rápido, sobre todo en Praga. Empiece a buscar bastante antes de que caduque su certificado de idioma.',
        ],
      },
      {
        en: [
          'Count on more than the sixty-day statutory period',
          'The law says sixty days from a complete file; in practice permanent residence cases run considerably longer.',
        ],
        pt: [
          'Contar com mais do que o prazo legal de sessenta dias',
          'A lei fala em sessenta dias a partir do processo completo; na prática os casos de residência permanente demoram bastante mais.',
        ],
        es: [
          'Contar con más del plazo legal de sesenta días',
          'La ley habla de sesenta días desde el expediente completo; en la práctica los casos de residencia permanente tardan bastante más.',
        ],
      },
      {
        en: [
          'Supply extra documents within the deadline given',
          'The procedure is suspended while you gather them, and missing the date given ends the case rather than delaying it.',
        ],
        pt: [
          'Entregar documentos adicionais no prazo indicado',
          'O procedimento fica suspenso enquanto você os reúne, e perder a data indicada encerra o caso em vez de o atrasar.',
        ],
        es: [
          'Aportar documentos adicionales en el plazo indicado',
          'El procedimiento queda suspendido mientras los reúne, y perder la fecha indicada archiva el caso en vez de retrasarlo.',
        ],
      },
    ],
    biometrics_health: [
      {
        en: [
          'Biometrics for the permanent residence card',
          'Taken once the decision is positive, with a further wait while the card is produced.',
        ],
        pt: [
          'Biometria para o cartão de residência permanente',
          'Recolhida quando a decisão é positiva, com nova espera enquanto o cartão é produzido.',
        ],
        es: [
          'Biometría para la tarjeta de residencia permanente',
          'Se toma una vez que la resolución es positiva, con otra espera mientras se produce la tarjeta.',
        ],
      },
      {
        en: [
          'Medical examination for permanent residence',
          'Not required; Czechia does not ask for one in this procedure.',
        ],
        pt: [
          'Exame médico para a residência permanente',
          'Não é exigido; a Chéquia não o pede neste procedimento.',
        ],
        es: [
          'Examen médico para la residencia permanente',
          'No se exige; Chequia no lo pide en este procedimiento.',
        ],
        priority: 3,
        required: false,
      },
    ],
    post_approval_steps: [
      {
        en: [
          'Collect the card issued for ten years',
          'The status itself is indefinite, but the plastic is valid for ten years and has to be exchanged before it expires.',
        ],
        pt: [
          'Levantar o cartão emitido por dez anos',
          'O estatuto em si é por tempo indeterminado, mas o plástico vale dez anos e tem de ser trocado antes de caducar.',
        ],
        es: [
          'Recoger la tarjeta expedida por diez años',
          'El estatuto en sí es indefinido, pero el plástico vale diez años y hay que cambiarlo antes de que caduque.',
        ],
      },
      {
        en: [
          'Move into the public health insurance system',
          'Permanent residents leave commercial policies and become insurees of the public system, which changes both what you pay and what is covered.',
        ],
        pt: [
          'Passar para o sistema público de seguro de saúde',
          'Residentes permanentes deixam as apólices comerciais e tornam-se segurados do sistema público, o que muda tanto o que se paga como o que fica coberto.',
        ],
        es: [
          'Pasar al sistema público de seguro de salud',
          'Los residentes permanentes dejan las pólizas comerciales y pasan a ser asegurados del sistema público, lo que cambia tanto lo que paga como lo que está cubierto.',
        ],
      },
      {
        en: [
          'Avoid absences longer than twelve consecutive months',
          'A continuous absence from the territory beyond that period ends the permanent residence, even though the card still looks valid.',
        ],
        pt: [
          'Evitar ausências superiores a doze meses seguidos',
          'Uma ausência contínua do território além desse período extingue a residência permanente, mesmo que o cartão ainda pareça válido.',
        ],
        es: [
          'Evitar ausencias de más de doce meses seguidos',
          'Una ausencia continua del territorio más allá de ese periodo extingue la residencia permanente, aunque la tarjeta siga pareciendo válida.',
        ],
      },
      {
        en: [
          'Report a change of address within thirty days',
          'The obligation continues after permanent residence is granted, and failing it is fined like any other reporting duty.',
        ],
        pt: [
          'Comunicar mudança de morada em trinta dias',
          'A obrigação continua depois de concedida a residência permanente, e o incumprimento é multado como qualquer outro dever de comunicação.',
        ],
        es: [
          'Comunicar el cambio de domicilio en treinta días',
          'La obligación sigue tras concederse la residencia permanente, y su incumplimiento se multa como cualquier otro deber de comunicación.',
        ],
      },
      {
        en: [
          'Count the years towards Czech citizenship',
          'Naturalisation normally asks for five years of permanent residence on top of what you already did, plus a B1 language exam and a test on Czech civics.',
        ],
        pt: [
          'Contar os anos rumo à cidadania checa',
          'A naturalização normalmente exige cinco anos de residência permanente além do que você já fez, mais um exame de idioma B1 e um teste de conhecimentos cívicos checos.',
        ],
        es: [
          'Contar los años de cara a la ciudadanía checa',
          'La naturalización suele exigir cinco años de residencia permanente además de lo ya recorrido, más un examen de idioma B1 y una prueba de conocimientos cívicos checos.',
        ],
        priority: 2,
        required: false,
      },
    ],
  },
};
