import type { CountryVisaSteps } from './types';
import { argentina } from './argentina';
import { australia } from './australia';
import { austria } from './austria';
import { belgium } from './belgium';
import { brazil } from './brazil';
import { canada } from './canada';
import { chile } from './chile';
import { china } from './china';
import { colombia } from './colombia';
import { costaRica } from './costa-rica';
import { croatia } from './croatia';
import { cyprus } from './cyprus';
import { czechia } from './czechia';
import { denmark } from './denmark';
import { dominicanRepublic } from './dominican-republic';
import { ecuador } from './ecuador';
import { egypt } from './egypt';
import { estonia } from './estonia';
import { finland } from './finland';
import { france } from './france';
import { germany } from './germany';
import { greece } from './greece';
import { hongKong } from './hong-kong';
import { hungary } from './hungary';
import { iceland } from './iceland';
import { india } from './india';
import { indonesia } from './indonesia';
import { ireland } from './ireland';
import { israel } from './israel';
import { italy } from './italy';
import { japan } from './japan';
import { luxembourg } from './luxembourg';
import { malaysia } from './malaysia';
import { malta } from './malta';
import { mexico } from './mexico';
import { morocco } from './morocco';
import { netherlands } from './netherlands';
import { newZealand } from './new-zealand';
import { norway } from './norway';
import { panama } from './panama';
import { paraguay } from './paraguay';
import { peru } from './peru';
import { philippines } from './philippines';
import { poland } from './poland';
import { portugal } from './portugal';
import { qatar } from './qatar';
import { romania } from './romania';
import { saudiArabia } from './saudi-arabia';
import { singapore } from './singapore';
import { southAfrica } from './south-africa';
import { southKorea } from './south-korea';
import { spain } from './spain';
import { sweden } from './sweden';
import { switzerland } from './switzerland';
import { taiwan } from './taiwan';
import { thailand } from './thailand';
import { turkey } from './turkey';
import { unitedArabEmirates } from './united-arab-emirates';
import { unitedKingdom } from './united-kingdom';
import { unitedStates } from './united-states';
import { uruguay } from './uruguay';
import { vietnam } from './vietnam';

/**
 * One entry per country, keyed by `countries.name` exactly as it appears in
 * `countries.seed.ts`. Splitting by country keeps each file reviewable and each
 * diff scoped to the country that actually changed.
 *
 * A country absent from here simply has no steps seeded. The seed is additive,
 * so filling this in over several rounds leaves no intermediate state that is
 * wrong — only incomplete.
 *
 * Generated by `build-registry.ts` from the files in this directory. Do not
 * edit by hand: add the country file and re-run the generator.
 *
 * Kept apart from `index.ts` so `validate.ts` can read it without constructing
 * a PrismaClient, which is what lets the checks run with no database.
 */
export const REGISTRY: Record<string, CountryVisaSteps> = {
  Argentina: argentina,
  Australia: australia,
  Austria: austria,
  Belgium: belgium,
  Brazil: brazil,
  Canada: canada,
  Chile: chile,
  China: china,
  Colombia: colombia,
  'Costa Rica': costaRica,
  Croatia: croatia,
  Cyprus: cyprus,
  Czechia: czechia,
  Denmark: denmark,
  'Dominican Republic': dominicanRepublic,
  Ecuador: ecuador,
  Egypt: egypt,
  Estonia: estonia,
  Finland: finland,
  France: france,
  Germany: germany,
  Greece: greece,
  'Hong Kong': hongKong,
  Hungary: hungary,
  Iceland: iceland,
  India: india,
  Indonesia: indonesia,
  Ireland: ireland,
  Israel: israel,
  Italy: italy,
  Japan: japan,
  Luxembourg: luxembourg,
  Malaysia: malaysia,
  Malta: malta,
  Mexico: mexico,
  Morocco: morocco,
  Netherlands: netherlands,
  'New Zealand': newZealand,
  Norway: norway,
  Panama: panama,
  Paraguay: paraguay,
  Peru: peru,
  Philippines: philippines,
  Poland: poland,
  Portugal: portugal,
  Qatar: qatar,
  Romania: romania,
  'Saudi Arabia': saudiArabia,
  Singapore: singapore,
  'South Africa': southAfrica,
  'South Korea': southKorea,
  Spain: spain,
  Sweden: sweden,
  Switzerland: switzerland,
  Taiwan: taiwan,
  Thailand: thailand,
  Turkey: turkey,
  'United Arab Emirates': unitedArabEmirates,
  'United Kingdom': unitedKingdom,
  'United States': unitedStates,
  Uruguay: uruguay,
  Vietnam: vietnam,
};
