export enum StepType {
  TARGET = 'TARGET',
  ENGLISH = 'ENGLISH',
  BUDGET = 'BUDGET',
  EDUCATION = 'EDUCATION',
  PROFESSIONAL = 'PROFESSIONAL',
  CLIMATE = 'CLIMATE',
  FAMILY = 'FAMILY',
  COUNTRY = 'COUNTRY',
}
